LABEL_MAPPING = {
   'car': 0,
   'policecar': 0,
   'bus': 1,
   'fireengine': 2,
   'truck': 2,
   'heavy_equipment': 2,
   'heavy-equipment': 2,
   'heavyequipment': 2,
   'flatbedtrailertruck': 2,
   'trailer': 2,
   'moto': 3,
   "motorcycle": 3,
   'pedestrian': 4,
   'ped': 4,
   'driver': 4,
   'rider': 4,
   'bike': 5,
   'cyclist': 5,
   "bicycle": 5,
   'traffic_cone': 6,
   'cone': 6,
   'barricade': 7,
   'movable_traffic_sign': 7,
   'movabletrafficsign': 7,
   'suv': 8,    # 'suv + van'
   'van': 8,
   'ambulance': 8,
   'lighttruck': 9,   # 'lighttruck + pickup'
   'pickup': 9,
}

LABEL_MAPPING_BLUR = {
    'car': 0,
   'policecar': 0,
   'bus': 0,
   'fireengine': 9,
   'truck': 9,
   'heavy_equipment': 9,
   'heavy-equipment': 9,
   'heavyequipment': 9,
   'flatbedtrailertruck': 9,
   'trailer': 9,
   'suv': 0,    # 'suv + van'
   'van': 0,
   'ambulance': 0,
   'lighttruck': 9,   # 'lighttruck + pickup'
   'pickup': 9,
   'moto': 3,
   "motorcycle": 3,
   'pedestrian': 4,
   'ped': 4,
   'driver': 4,
   'rider': 4,
   'bike': 5,
   'cyclist': 5,
   "bicycle": 5,
   'traffic_cone': 6,
   'cone': 6,
   'barricade': 7,
   'movable_traffic_sign': 7,
   'movabletrafficsign': 7,
}

BASIC_COLORS = {
    0: (255,0,0),
    1: (202,235,216),
    2: (255,255,0),
    3: (0, 255, 0),
    4: (0, 0, 255),
    5: (128,42,42),
    6: (0, 255, 255),
    7: (255, 0, 255),
    10: (192, 192, 192),
    11: (128, 128, 128),
    "Maroon": (128, 0, 0),
    "Olive": (128, 128, 0),
    8: (0, 128, 0),
    9: (128, 0, 128),
    "Teal": (0, 128, 128)
}

NAME_ABBRE = {
   'car': 'car',
   'policecar': 'car',
   'bus': 'bus',
   'fireengine': 'tru',
   'truck': 'tru',
   'heavy_equipment': 'tru',
   'heavy-equipment': 'tru',
   'heavyequipment': 'tru',
   'flatbedtrailertruck': 'tru',
   'trailer': 'tru',
   'moto': 'moto',
   "motorcycle": 'moto',
   'pedestrian': 'ped',
   'ped': 'ped',
   'driver': 'ped',
   'rider': 'ped',
   'bike': 'bike',
   'cyclist': 'bike',
   "bicycle": 'bike',
   'traffic_cone': 'cone',
   'cone': 'cone',
   'barricade': 'bar',
   'movable_traffic_sign': 'bar',
   'movabletrafficsign': 'bar',
   'suv': 'suv',    # 'suv + van'
   'van': 'suv',
   'ambulance': 'suv',
   'lighttruck': 'lig',   # 'lighttruck + pickup'
   'pickup': 'lig'
}